# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swarm < Formula
  desc "Swarm CLI — provision VMs and deploy devcontainers"
  homepage "https://github.com/hyperengineering/swarm"
  version "0.8.0-beta.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyperengineering/homebrew-tap/raw/main/binaries/swarm_0.8.0-beta.2_darwin_amd64.tar.gz"
      sha256 "41dec913da48b214caef623ff85ed635311260296b3678ddc231450db716fefe"

      define_method(:install) do
        bin.install "swarm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hyperengineering/homebrew-tap/raw/main/binaries/swarm_0.8.0-beta.2_darwin_arm64.tar.gz"
      sha256 "57aa743d707437f3c4ad2bc6e8214ccfa295473a8a7875c8e4456bd77b940447"

      define_method(:install) do
        bin.install "swarm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/homebrew-tap/raw/main/binaries/swarm_0.8.0-beta.2_linux_amd64.tar.gz"
      sha256 "8084147c9883214dd7daf0ace382559165bed698280b62a7066ec3c0a9855d9f"
      define_method(:install) do
        bin.install "swarm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/homebrew-tap/raw/main/binaries/swarm_0.8.0-beta.2_linux_arm64.tar.gz"
      sha256 "88e83d682fec149a0a84c92c34c7621c2aad8ea82826db219e15dd05847a67ad"
      define_method(:install) do
        bin.install "swarm"
      end
    end
  end

  test do
    system "#{bin}/swarm", "version"
  end
end
