# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Centralized lore persistence and synchronization service"
  homepage "https://github.com/hyperengineering/engram"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyperengineering/engram/releases/download/v1.1.1/engram_darwin_amd64.tar.gz"
      sha256 "9662c19d973e8316131ddaa3cb78950b6034f57dd6bc51f7efe4342140ef9935"

      def install
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hyperengineering/engram/releases/download/v1.1.1/engram_darwin_arm64.tar.gz"
      sha256 "b06bd2d06142c1d042e7535f635a51e12c9d14a890424ec74f01e7260e053c63"

      def install
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/engram/releases/download/v1.1.1/engram_linux_amd64.tar.gz"
      sha256 "76ac70f4f47cda20ab1aa6789340fa582f5a26c96c88007a042feef3ce0acf15"
      def install
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/engram/releases/download/v1.1.1/engram_linux_arm64.tar.gz"
      sha256 "47a36caa3c94b479b07d6d1590d9afbbdd9991f672aad3549c997277f9f46b1f"
      def install
        bin.install "engram"
      end
    end
  end

  test do
    system "#{bin}/engram", "version"
  end
end
