# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Engram < Formula
  desc "Centralized lore persistence and synchronization service"
  homepage "https://github.com/hyperengineering/engram"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyperengineering/engram/releases/download/v1.3.1/engram_darwin_amd64.tar.gz"
      sha256 "f88e7b5af0232dd1b6881069150251abd6c8bb7c8001faf94b2d96debe0a5f35"

      def install
        bin.install "engram"
        # Install wrapper script
        (bin/"engram-wrapper").write <<~EOS
          #!/bin/bash
          set -e
          ENV_FILE="#{etc}/engram/environment"
          if [[ -f "$ENV_FILE" ]]; then
            set -a
            source "$ENV_FILE"
            set +a
          fi
          exec "#{bin}/engram" "$@"
        EOS
        (bin/"engram-wrapper").chmod 0755

        # Create config directory and environment template
        (etc/"engram").mkpath
        (var/"engram").mkpath
        (var/"log/engram").mkpath

        # Install environment template (don't overwrite existing)
        unless (etc/"engram/environment").exist?
          (etc/"engram/environment").write <<~EOS
            # Engram Environment Variables
            # Permissions: 600 (chmod 600 #{etc}/engram/environment)

            # Required: API key for authenticating clients
            # Generate: openssl rand -hex 32
            ENGRAM_API_KEY=

            # Required: OpenAI API key for embedding generation
            # Get from: https://platform.openai.com/api-keys
            OPENAI_API_KEY=

            # Optional: Override default port (8080)
            # ENGRAM_PORT=8080

            # Optional: Override default host (localhost)
            # ENGRAM_HOST=0.0.0.0
          EOS
          (etc/"engram/environment").chmod 0600
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hyperengineering/engram/releases/download/v1.3.1/engram_darwin_arm64.tar.gz"
      sha256 "60676633f238b01d441f76d21181a4aad3f58a0f7f9d0ecc39550b175f8cbd78"

      def install
        bin.install "engram"
        # Install wrapper script
        (bin/"engram-wrapper").write <<~EOS
          #!/bin/bash
          set -e
          ENV_FILE="#{etc}/engram/environment"
          if [[ -f "$ENV_FILE" ]]; then
            set -a
            source "$ENV_FILE"
            set +a
          fi
          exec "#{bin}/engram" "$@"
        EOS
        (bin/"engram-wrapper").chmod 0755

        # Create config directory and environment template
        (etc/"engram").mkpath
        (var/"engram").mkpath
        (var/"log/engram").mkpath

        # Install environment template (don't overwrite existing)
        unless (etc/"engram/environment").exist?
          (etc/"engram/environment").write <<~EOS
            # Engram Environment Variables
            # Permissions: 600 (chmod 600 #{etc}/engram/environment)

            # Required: API key for authenticating clients
            # Generate: openssl rand -hex 32
            ENGRAM_API_KEY=

            # Required: OpenAI API key for embedding generation
            # Get from: https://platform.openai.com/api-keys
            OPENAI_API_KEY=

            # Optional: Override default port (8080)
            # ENGRAM_PORT=8080

            # Optional: Override default host (localhost)
            # ENGRAM_HOST=0.0.0.0
          EOS
          (etc/"engram/environment").chmod 0600
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/engram/releases/download/v1.3.1/engram_linux_amd64.tar.gz"
      sha256 "e05bb9fe9115bfcda1021676d09be77a8d24a857615bad62c8c518f7a57cc461"
      def install
        bin.install "engram"
        # Install wrapper script
        (bin/"engram-wrapper").write <<~EOS
          #!/bin/bash
          set -e
          ENV_FILE="#{etc}/engram/environment"
          if [[ -f "$ENV_FILE" ]]; then
            set -a
            source "$ENV_FILE"
            set +a
          fi
          exec "#{bin}/engram" "$@"
        EOS
        (bin/"engram-wrapper").chmod 0755

        # Create config directory and environment template
        (etc/"engram").mkpath
        (var/"engram").mkpath
        (var/"log/engram").mkpath

        # Install environment template (don't overwrite existing)
        unless (etc/"engram/environment").exist?
          (etc/"engram/environment").write <<~EOS
            # Engram Environment Variables
            # Permissions: 600 (chmod 600 #{etc}/engram/environment)

            # Required: API key for authenticating clients
            # Generate: openssl rand -hex 32
            ENGRAM_API_KEY=

            # Required: OpenAI API key for embedding generation
            # Get from: https://platform.openai.com/api-keys
            OPENAI_API_KEY=

            # Optional: Override default port (8080)
            # ENGRAM_PORT=8080

            # Optional: Override default host (localhost)
            # ENGRAM_HOST=0.0.0.0
          EOS
          (etc/"engram/environment").chmod 0600
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/engram/releases/download/v1.3.1/engram_linux_arm64.tar.gz"
      sha256 "ed5b01275761ef5ebfbf2842b15e7eeef120678e015cc1ce6df643660e3f1fdf"
      def install
        bin.install "engram"
        # Install wrapper script
        (bin/"engram-wrapper").write <<~EOS
          #!/bin/bash
          set -e
          ENV_FILE="#{etc}/engram/environment"
          if [[ -f "$ENV_FILE" ]]; then
            set -a
            source "$ENV_FILE"
            set +a
          fi
          exec "#{bin}/engram" "$@"
        EOS
        (bin/"engram-wrapper").chmod 0755

        # Create config directory and environment template
        (etc/"engram").mkpath
        (var/"engram").mkpath
        (var/"log/engram").mkpath

        # Install environment template (don't overwrite existing)
        unless (etc/"engram/environment").exist?
          (etc/"engram/environment").write <<~EOS
            # Engram Environment Variables
            # Permissions: 600 (chmod 600 #{etc}/engram/environment)

            # Required: API key for authenticating clients
            # Generate: openssl rand -hex 32
            ENGRAM_API_KEY=

            # Required: OpenAI API key for embedding generation
            # Get from: https://platform.openai.com/api-keys
            OPENAI_API_KEY=

            # Optional: Override default port (8080)
            # ENGRAM_PORT=8080

            # Optional: Override default host (localhost)
            # ENGRAM_HOST=0.0.0.0
          EOS
          (etc/"engram/environment").chmod 0600
        end
      end
    end
  end

  def caveats
    <<~EOS
      To complete setup:

        1. Configure your API keys:
           nano #{etc}/engram/environment

           Set ENGRAM_API_KEY and OPENAI_API_KEY

        2. Start the service:
           brew services start engram

        3. Verify it's running:
           curl http://localhost:8080/api/v1/health

      Configuration: #{etc}/engram/environment
      Data:          #{var}/engram/
      Logs:          #{var}/log/engram/engram.log
    EOS
  end

  service do
    run [opt_bin/"engram-wrapper"]
    working_dir var/"engram"
    log_path var/"log/engram/engram.log"
    error_log_path var/"log/engram/engram.log"
    keep_alive true
  end

  test do
    system "#{bin}/engram", "version"
  end
end
