# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recall < Formula
  desc "CLI for managing experiential lore from AI agent workflows"
  homepage "https://github.com/hyperengineering/recall"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyperengineering/recall/releases/download/v1.0.4/recall_1.0.4_darwin_amd64.tar.gz"
      sha256 "c796e54d0ae4ddb6159098d5c6f4ded97ced78629e23019418302fd69b084158"

      def install
        bin.install "recall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hyperengineering/recall/releases/download/v1.0.4/recall_1.0.4_darwin_arm64.tar.gz"
      sha256 "bacb2c0303122846caf9d56f898c4c4866096c9974362c5de967c05ef3ab0d10"

      def install
        bin.install "recall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/recall/releases/download/v1.0.4/recall_1.0.4_linux_amd64.tar.gz"
      sha256 "67fcedddc843477c75d8291408f591a5cc86d3be47ed6d89a87091da8f35cb52"
      def install
        bin.install "recall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/recall/releases/download/v1.0.4/recall_1.0.4_linux_arm64.tar.gz"
      sha256 "2231351f6677843be06aa8052cd9a2b274a9de3960eaed6bd0d872a036077500"
      def install
        bin.install "recall"
      end
    end
  end

  test do
    system "#{bin}/recall", "version"
  end
end
