# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recall < Formula
  desc "CLI for managing experiential lore from AI agent workflows"
  homepage "https://github.com/hyperengineering/recall"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyperengineering/recall/releases/download/v1.2.1/recall_1.2.1_darwin_amd64.tar.gz"
      sha256 "15a3e0cc26646fe8ccaf79f511b208b0c02d3f3295c2b93913eb111b53c31f87"

      def install
        bin.install "recall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hyperengineering/recall/releases/download/v1.2.1/recall_1.2.1_darwin_arm64.tar.gz"
      sha256 "a631bfe50aebf31525e3a44857e8770a4885c090657cf201616998b3110d87d4"

      def install
        bin.install "recall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/recall/releases/download/v1.2.1/recall_1.2.1_linux_amd64.tar.gz"
      sha256 "125b55a2cf799537e03d16e9fc0810479ea2729589c25b331a25c8946a14a957"
      def install
        bin.install "recall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyperengineering/recall/releases/download/v1.2.1/recall_1.2.1_linux_arm64.tar.gz"
      sha256 "bcf0200dd63cb6c659a47f8f13e9a8c2496bcbd3270948b57d5394ec02121333"
      def install
        bin.install "recall"
      end
    end
  end

  test do
    system "#{bin}/recall", "version"
  end
end
